spring:
  data:
    redis:
      database: 0
      port: 6379
      password: 123456
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000